window.GPT4O_CREDITS = [
  { name: "-Zho-", url: "https://x.com/ZHO_ZHO_ZHO" },
  { name: "Peter的AI学习笔记", url: "https://x.com/zhngyhu87231643?s=21"},
  { name: "jamez-bondos", url: "https://github.com/jamez-bondos" },
  { name: "Gizem Akdag", url: "https://x.com/gizakdag" },
  { name: "宝玉", url: "https://x.com/dotey" },
  { name: "balconychy(贝壳里奇)", url: "https://x.com/balconychy" },
  { name: "Daniel", url: "https://x.com/0xdlk" },
  { name: "RichChat", url: "https://x.com/richardchang" },
  { name: "归藏(guizang.ai)", url: "https://x.com/op7418" },
  { name: "katon", url: "https://x.com/hellokaton" },
  { name: "Berryxia.AI", url: "https://x.com/berryxia_ai" },
  { name: "Ege", url: "https://x.com/egeberkina" },
  { name: "Brett", url: "https://x.com/BrettFromDJ" },
  { name: "89'S", url: "https://x.com/M_w14_" },
  { name: "jiamimao 猫叔", url: "https://x.com/jiamimaodashu" },
  { name: "Amira Zairi", url: "https://x.com/azed_ai" },
  { name: "Umesh", url: "https://x.com/umesh_ai" },
  { name: "Michael Rabone", url: "https://x.com/michaelrabone" },
  { name: "gnrly.xyz", url: "https://x.com/gnrlyxyz" },
  { name: "f-is-h", url: "https://github.com/f-is-h" },
  { name: "Madpencil", url: "https://x.com/madpencil_" },
  { name: "Hewar", url: "https://x.com/hewarsaber" }
];
